apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
spec:
  containers:
  - name: database-pv
    image: mysql
    ports:
    - containerPort: 8080
    env:
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
      name: MYSQL_ROOT_PASSWORD
      value: password
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: myvolume2
  volumes:
  - name: myvolume2
    persistentVolumeClaim:
      claimName: pvc