apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    app: pv 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data-pv
    type: DirectoryOrCreate